import { Card, CardContent, CardHeader, CardTitle } from "~components/ui/card";
import { Separator } from "~components/ui/separator";
import { WebsiteLogo } from "~app/components/logo";

export default function TermsOfService() {
  return (
    <div className="min-h-screen">
      <div className="container mx-auto px-4 py-8 max-w-4xl space-y-8">
        <WebsiteLogo />
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="text-2xl">Terms of Use</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <p className="leading-relaxed italic">
              Last updated: July 13, 2025
            </p>
            <p className="leading-relaxed">
              Please read these Terms of Use (“Terms”) carefully before using
              the Website Scam Detection Tool browser extension (Fraudvisor). By
              installing or using Fraudvisor, you agree to be bound by these
              Terms. If you do not agree, do not install or use Fraudvisor.
            </p>
            <section>
              <h3 className="text-lg font-semibold mb-3">
                1. Acceptance of Terms
              </h3>
              <p className="leading-relaxed">
                By accessing or using Fraudvisor, you confirm that you are at
                least 18 years of age and have the legal capacity to enter into
                these Terms. If you are using Fraudvisor on behalf of an
                organization, you represent that you have authority to bind that
                organization.
              </p>
            </section>

            <Separator />

            <section>
              <h3 className="text-lg font-semibold mb-3">2. Use License</h3>
              <p className=" leading-relaxed mb-3">
                We grant you a limited, non-exclusive, non-transferable,
                revocable license to install and use Fraudvisor solely for your
                personal or organization’s internal purposes, subject to these
                Terms. This is the grant of a license, not a transfer of title,
                and under this license you may not:
              </p>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li>modify or copy the software</li>
                <li>Reverse engineer, decompile, or disassemble Fraudvisor.</li>
                <li>Use Fraudvisor to infringe any third-party rights.</li>
                <li>
                  Use Fraudvisor for any spying, monitoring, or surveillance
                  purposes.
                </li>
                <li>
                  Remove, alter, or obscure any proprietary notices on
                  Fraudvisor.
                </li>
              </ul>
            </section>

            <Separator />

            <section>
              <h3 className="text-lg font-semibold mb-3">3. Permitted Uses</h3>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li>Checking websites you visit for potential scams.</li>
                <li>
                  Viewing summary and detailed reports generated by Fraudvisor.
                </li>
              </ul>
            </section>

            <Separator />

            <section>
              <h3 className="text-lg font-semibold mb-3">4. User Accounts</h3>
              <p className=" leading-relaxed">
                When you create an account with us, you must provide information
                that is accurate, complete, and current at all times. You are
                responsible for safeguarding the password and for all activities
                that occur under your account. We do not ask for any personal
                information, the communication to users will be only via mail
                from the domain "fraudvisor.org" and no other source.
              </p>
            </section>

            <Separator />

            <section>
              <h3 className="text-lg font-semibold mb-3">5. Prohibited Uses</h3>
              <p className=" leading-relaxed mb-3">
                You may not use Fraudvisor to:
              </p>
              <ul className="list-disc list-inside space-y-1 ml-4">
                <li>
                  For any unlawful purpose or to solicit others to perform
                  unlawful acts
                </li>
                <li>
                  To violate any international, federal, provincial, or state
                  regulations, rules, laws, or local ordinances
                </li>
                <li>
                  To infringe upon or violate our intellectual property rights
                  or the intellectual property rights of others
                </li>
                <li>
                  To harass, abuse, insult, harm, defame, slander, disparage,
                  intimidate, or discriminate
                </li>
                <li>To submit false or misleading information</li>
              </ul>
            </section>

            <Separator />

            <section>
              <h3 className="text-lg font-semibold mb-3">
                5. Third-Party Services
              </h3>
              <p className=" leading-relaxed">
                Fraudvisor relies on third-party APIs (e.g., Google Search API,
                OpenAI GPT-4) and public internet sources (e.g., Reddit,
                Twitter, ScamAdviser, Trustpilot) to analyze websites and gather
                reviews. Your use of those APIs is subject to their respective
                terms and privacy policies.
              </p>
            </section>

            <Separator />

            <section>
              <h3 className="text-lg font-semibold mb-3">6. Disclaimer</h3>
              <p className=" leading-relaxed">
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>
                    <strong>Accuracy:</strong> Fraudvisor provides risk
                    assessments based on automated analysis and third-party
                    data. We do not guarantee that any website flagged as “scam”
                    or “safe” is actually fraudulent or legitimate.
                  </li>
                  <li>
                    <strong>No Warranty:</strong> FRAUDVISOR IS PROVIDED “AS IS”
                    AND “AS AVAILABLE” WITHOUT WARRANTIES OF ANY KIND, WHETHER
                    EXPRESS OR IMPLIED.
                  </li>
                </ul>
              </p>
            </section>

            <Separator />

            <section>
              <h3 className="text-lg font-semibold mb-3">
                7. Limitation of Liability
              </h3>
              <p className=" leading-relaxed">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL WE BE
                LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE
                DAMAGES ARISING OUT OF YOUR USE OF FRAUDVISOR, EVEN IF ADVISED
                OF THE POSSIBILITY OF SUCH DAMAGES.
              </p>
            </section>

            <Separator />

            <section>
              <h3 className="text-lg font-semibold mb-3">8. Termination</h3>
              <p className=" leading-relaxed">
                We may terminate or suspend your account and bar access to the
                service immediately, without prior notice or liability, under
                our sole discretion, for any reason whatsoever and without
                limitation, for conduct that we believe violates these Terms or
                is harmful to others.
              </p>
            </section>

            <Separator />

            <section>
              <h3 className="text-lg font-semibold mb-3">9. Governing Law</h3>
              <p className=" leading-relaxed">
                These Terms are governed by the laws of India, without regard to
                conflict-of-law principles.
              </p>
            </section>

            <Separator />

            <section>
              <h3 className="text-lg font-semibold mb-3">
                8. Changes to Terms
              </h3>
              <p className=" leading-relaxed">
                We reserve the right, at our sole discretion, to modify or
                replace these Terms at any time. If a revision is material, we
                will provide at least 30 days notice prior to any new terms
                taking effect.
              </p>
            </section>
          </CardContent>
        </Card>

        {/* Contact Information */}
        <Card>
          <CardHeader>
            <CardTitle className="text-xl">Questions About Terms?</CardTitle>
          </CardHeader>
          <CardContent>
            <p className=" leading-relaxed">
              If you have any questions about these Terms of Service, please
              contact us at:
            </p>
            <div className="mt-4 space-y-2">
              <p className="">
                <strong>Email:</strong> legal@fraudvisor.org
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
